### ISSUE TITLE
have to add quill.show.css?

### ISSUE THREAD

**Issue by tf0054** [benhowell/reagent-quill#3]
I guess we have to add not only core.css but also snow.css to show the editor correctly.

https://cdnjs.cloudflare.com/ajax/libs/quill/1.1.0/quill.snow.css

**Comment by benhowell** [comment]
That's right. Although technically, that's just one theme, it is however still the only theme.

**Comment by tf0054** [comment]
Ah, thank you for your comment. I had a broken layout with only core.css. So core.css and snow.css are needed to include. my bad!
